# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:04:36+00:00

from __future__ import annotations

from typing import Any, List

from pydantic import RootModel


class ApodGetResponse(RootModel[List[Any]]):
    root: List[Any]
